### ISSUE TITLE
Do not override boot method, prevents any other trait from working

### ISSUE THREAD

**Issue by crissi** [cviebrock/eloquent-typecast#1]
There is something about how to avoid this here: http://laravel.com/docs/eloquent#global-scopes

**Comment by cviebrock** [comment]
Thanks! I'm on vacation for a bit, but will definitely "fix" this when I return. 
- Colin

**Comment by nateweisiger** [comment]
+1

**Comment by cviebrock** [comment]
Can you guys test the `dev-master` package and see if that solves your issues?

**Comment by nateweisiger** [comment]
It's looking good! I'll let you know if I see anything else.

Thanks Colin,
Nate

**Comment by Torann** [comment]
Looks good

**Comment by cviebrock** [comment]
Cool!
